// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJ63nns6D0fvFtInsCn41BmH1e23Soog',
    appId: '1:1057675349160:web:c185c2cd0815d4aa15469d',
    messagingSenderId: '1057675349160',
    projectId: 'nyarongo',
    authDomain: 'nyarongo.firebaseapp.com',
    storageBucket: 'nyarongo.firebasestorage.app',
    measurementId: 'G-3L0JKD2PLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmI3cZCyD-DtzJ-tH51KZCjbk2Zv2Fx0E',
    appId: '1:1057675349160:android:ef83703ffd8bd39a15469d',
    messagingSenderId: '1057675349160',
    projectId: 'nyarongo',
    storageBucket: 'nyarongo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0LJh2v8FompwCXUZzBU6IBdJOKQcicA',
    appId: '1:1057675349160:ios:99f54c9ba70f232115469d',
    messagingSenderId: '1057675349160',
    projectId: 'nyarongo',
    storageBucket: 'nyarongo.firebasestorage.app',
    iosBundleId: 'com.example.nyarongoWholesale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ0LJh2v8FompwCXUZzBU6IBdJOKQcicA',
    appId: '1:1057675349160:ios:99f54c9ba70f232115469d',
    messagingSenderId: '1057675349160',
    projectId: 'nyarongo',
    storageBucket: 'nyarongo.firebasestorage.app',
    iosBundleId: 'com.example.nyarongoWholesale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSJ63nns6D0fvFtInsCn41BmH1e23Soog',
    appId: '1:1057675349160:web:ed4d124828b872a815469d',
    messagingSenderId: '1057675349160',
    projectId: 'nyarongo',
    authDomain: 'nyarongo.firebaseapp.com',
    storageBucket: 'nyarongo.firebasestorage.app',
    measurementId: 'G-CKNWRV55MK',
  );

}